config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#one"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioGuiado</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <nav class="navbar-inverse">

      <!-- Links -->
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "one", pages_one_path %></li>
        <li class="nav-item"><%= link_to "two", pages_two_path %></li>
        <li class="nav-item"><%= link_to "three", pages_three_path %></li>
      </ul>
    </nav>
    
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Alejandra Vilches Villena</h1>

app/views/pages/three.html.erb
<h2>Probando agregar una página</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen boo.k</p>

app/views/pages/two.html.erb
<h1>Captura de pantalla desafío</h1>
<%= image_tag "rails.routes"%>